package app.locallexis.data.db

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Schema-export checks.
 *
 * Asserts each database version's schema JSON is generated by KSP into
 * `schemas/` with the expected tables/columns. The v1 -> v2 migration path
 * itself is covered by [Migration1To2Test], which runs MigrationTestHelper
 * under Robolectric with the exported schemas served from the debug
 * variant's merged assets (see build.gradle.kts).
 */
class MigrationTest {

    @Test
    fun schemaV1IsExported() {
        val schema = File(SCHEMA_DIR, "1.json")
        assertTrue(
            "v1 schema missing at ${schema.absolutePath}. " +
                "Check ksp { arg(\"room.schemaLocation\", ...) } in build.gradle.kts.",
            schema.exists(),
        )
        val text = schema.readText()
        // Spot-check the entity tables made it into the export.
        for (table in listOf("transcripts", "segments", "segments_fts", "speakers", "devices", "sync_state")) {
            assertTrue(
                "schema missing table '$table'",
                text.contains("\"tableName\": \"$table\""),
            )
        }
    }

    @Test
    fun schemaV2IsExported() {
        val schema = File(SCHEMA_DIR, "2.json")
        assertTrue(
            "v2 schema missing at ${schema.absolutePath} — bump @Database version and rebuild.",
            schema.exists(),
        )
        val text = schema.readText()
        for (column in listOf("title", "summary", "summaryModel", "summaryCreatedAt")) {
            assertTrue("v2 schema missing column '$column'", text.contains("\"columnName\": \"$column\""))
        }
    }

    companion object {
        private val SCHEMA_DIR = File("schemas/app.locallexis.data.db.LocalLexisDatabase")
    }
}
